version: "3.1"
services:
    www:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./Muziekproject:/var/www/html
            - ./conf/config.inc.php:/etc/phpmyadmin/config.inc.php
            - ./conf/httpd-xampp.conf:/opt/lampp/etc/extra/httpd-xampp.conf
            - ./var/mysql:/opt/lampp/var/mysql
